### PR TITLE
Use stylelint rather than sass-lint for scss linting

### PR DESCRIPTION
**Pull request by teceler**
Sass-lint is unmaintained

### CODE REVIEW

**Comment by teceler** [comment]
Sass-lint rules I cannot currently replicate in stylelint:
- no-misspelled-properties
- bem-depth
- border-zero
- property-sort-order (disabled anyway)
- shorthand-values (shorthand-property-no-redundant-values is stricter than the setting we were using)

Sass-lint rules I have partially replicated in stylelint:
- pseudo-element (sass-lint rule prevents single-colon classes)
- space-around-operator (in most places but not in all functions)

Rules I think I have successfully replicated, but am not entirely sure
- brace-style

**Comment by Throne3d** [comment]
This is done now we've migrated to GitHub Actions, right? Should we close this? 🙌

**Comment by teceler** [comment]
> This is done now we've migrated to GitHub Actions, right? Should we close this? raised_hands

We're still using sass-lint and -- I think on codeclimate? I do have the reviewdog PR in here though I think yes

**Comment by Throne3d** [comment]
Oh, oops, I think I misread where we had the stylelint check and thought it was already merged! If we rebase this maybe it can merge? I don't remember if this was blocked on something (since it's marked as Draft).

**Comment by Throne3d** [comment]
About rules we can't replicate:

- no-misspelled-properties - should be possible with [property-no-unknown](https://stylelint.io/user-guide/rules/list/property-no-unknown/)
- [bem-depth](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/bem-depth.md) - BEM seems to be a special way of writing selectors, which we don't use, so I'm fine ignoring this
- [border-zero](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/border-zero.md) - don't personally mind about this
- property-sort-order (disabled anyway) - seems fine to ignore
- shorthand-values - I don't mind what we do here!

I think given the property-no-unknown lint we should be good? We could add it to the config and see how it goes!

**Review by Throne3d — APPROVED** [review]

**Pull request merged**
