### PR TITLE
Upgrade gems: rake, patch-fuzzy versions

### PR DESCRIPTION
**Pull request by Throne3d**
**Edit**: remove the seed_dump update since it looks like it might be breaking tests.

### CODE REVIEW

**Comment by greysteil** [comment]
Looks like you're already pretty up-to-date, but would you be up for automatically creating dependency update PRs in the future? I built [Dependabot](https://dependabot.com) to do that at my last company - it puts in a PR every time there's a new version of one of your dependencies. Could be a time-saver, and we made it free for open source. Worth checking out? There's an example PR [here](https://github.com/greysteil/ossfriday/pull/9).

**Comment by Throne3d** [comment]
@greysteil I actually have no idea who you are! Or if we should be using your service, or if this is an automatic message?

We're currently using Gemnasium and I just haven't set it up to automatically update (they have a new beta feature to do that).

**Comment by greysteil** [comment]
Haha, not an automated message - I've just been looking through GitHub PRs at the way people handle dependency updates to figure out the best way.

Gemnasium's pretty good - we used it at GoCardless when I was there, but never got on with the automated updates (has been in beta for years...). Built Dependabot to fix the shortcomings (we wanted one PR per dependency, for them to auto-rebase, and not to come from someone's laptop - not sure if Gemnasium have changed all that stuff now). Give it a go if you fancy, but I won't be offended if not!

**Comment by Marri** [comment]
Other than Gemnasium, we are still pretty manual about dependency updates, comes of being a side project maintained by two people in their spare time :D Thank you for the link, we will take a look!

**Comment by greysteil** [comment]
It's how lots of the best things start 🙂

**Pull request merged**
